### ISSUE TITLE
Add isort to the project

### ISSUE THREAD

**Issue by saeedghx68** [mirzakhany/django_boilerplate#24]
@peymanslh Hi Peyman, Is it possible for you to do that?

**Comment by peymanslh** [comment]
I checked our pre-commit config, and we using it already: [link1](https://github.com/mirzakhany/django_boilerplate/blob/236e10bad0126f34b4e63c90f71187469e2061cf/.pre-commit-config.yaml#L6) - [link2](https://github.com/mirzakhany/django_boilerplate/blob/236e10bad0126f34b4e63c90f71187469e2061cf/.pre-commit-config.yaml#L10)

**Comment by saeedghx68** [comment]
> I checked our pre-commit config, and we using it already: [link1](https://github.com/mirzakhany/django_boilerplate/blob/236e10bad0126f34b4e63c90f71187469e2061cf/.pre-commit-config.yaml#L6) - [link2](https://github.com/mirzakhany/django_boilerplate/blob/236e10bad0126f34b4e63c90f71187469e2061cf/.pre-commit-config.yaml#L10)

Then we need to add to the requirements file and also config it

**Comment by peymanslh** [comment]
Ok, sure.
I'm working on it. 👍🏻
